# Generated by Django 3.1.4 on 2021-01-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210106_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='active',
            new_name='status',
        ),
    ]
