# Generated by Django 3.1.4 on 2021-01-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_dislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
